//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLSScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLSScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Title&quot;: &quot;LSA-1&quot;,
        ///        &quot;Units&quot;: {
        ///            &quot;1&quot;: &quot;Facts about Sloths&quot;,
        ///            &quot;2&quot;: &quot;Gladiators&quot;,
        ///            &quot;3&quot;: &quot;Meet Joey&quot;,
        ///            &quot;4&quot;: &quot;Your ID, Please!&quot;,
        ///            &quot;5&quot;: &quot;Don&apos;t Bite Me!&quot;,
        ///            &quot;6&quot;: &quot;Get the Ball Rolling&quot;,
        ///            &quot;7&quot;: &quot;Why Do We Sleep?&quot;,
        ///            &quot;8&quot;: &quot;Saving Energy&quot;
        ///        }
        ///    },
        ///    {
        ///        &quot;Title&quot;: &quot;LSA-2&quot;,
        ///        &quot;Units&quot;: {
        ///            &quot;1&quot;: &quot;Pyramids&quot;,
        ///            &quot;2&quot;: &quot;Moko to the Rescue&quot;,
        ///            &quot;3&quot;: &quot;Whi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    &quot;LSA-1&quot;,
        ///    &quot;LSA-2&quot;,
        ///    &quot;LSB-1&quot;,
        ///    &quot;LSB-2&quot;,
        ///    &quot;LSC-1&quot;,
        ///    &quot;LSC-2&quot;,
        ///    &quot;LSD-1&quot;,
        ///    &quot;LSD-2&quot;
        ///].
        /// </summary>
        public static string ClassLevels {
            get {
                return ResourceManager.GetString("ClassLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;7/27/2015&quot;: &quot;JLS Summer Holiday Day 1&quot;,
        ///    &quot;7/28/2015&quot;: &quot;JLS Summer Holiday Day 1&quot;,
        ///    &quot;7/29/2015&quot;: &quot;JLS Summer Holiday Day 1&quot;,
        ///    &quot;7/30/2015&quot;: &quot;JLS Summer Holiday Day 1&quot;,
        ///    &quot;7/31/2015&quot;: &quot;JLS Summer Holiday Day 1&quot;,
        ///    &quot;12/21/2015&quot;: &quot;JLS Winter Holiday Day 1&quot;,
        ///    &quot;12/22/2015&quot;: &quot;JLS Winter Holiday Day 2&quot;,
        ///    &quot;12/23/2015&quot;: &quot;JLS Winter Holiday Day 3&quot;,
        ///    &quot;12/24/2015&quot;: &quot;JLS Winter Holiday Day 4&quot;,
        ///    &quot;12/25/2015&quot;: &quot;JLS Winter Holiday Day 5&quot;
        ///}.
        /// </summary>
        public static string JLSHolidays {
            get {
                return ResourceManager.GetString("JLSHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;1/1/2015&quot;: &quot;New Year&apos;s Day&quot;,
        ///    &quot;2/18/2015&quot;: &quot;Seollal Holiday Day 1&quot;,
        ///    &quot;2/19/2015&quot;: &quot;Seollal Holiday Day 2&quot;,
        ///    &quot;2/20/2015&quot;: &quot;Seollal Holiday Day 3&quot;,
        ///    &quot;3/1/2015&quot;: &quot;Independence Movement Day&quot;,
        ///    &quot;5/5/2015&quot;: &quot;Children&apos;s Day&quot;,
        ///    &quot;5/25/2015&quot;: &quot;Buddha&apos;s Birthday&quot;,
        ///    &quot;6/6/2015&quot;: &quot;Memorial Day&quot;,
        ///    &quot;8/15/2015&quot;: &quot;Liberation Day&quot;,
        ///    &quot;9/26/2015&quot;: &quot;Chuesok Festival Day 1&quot;,
        ///    &quot;9/27/2015&quot;: &quot;Chuseok Festival Day 2&quot;,
        ///    &quot;9/28/2015&quot;: &quot;Chuseok Festival Day 3&quot;,
        ///    &quot;9/29/2015&quot;: &quot;Chuseo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KRHolidays {
            get {
                return ResourceManager.GetString("KRHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	[
        ///        &quot;2:30-3:10&quot;,
        ///        &quot;3:10-3:50&quot;,
        ///        &quot;3:55-4:45&quot;,
        ///        &quot;4:45-5:35&quot;,
        ///        &quot;5:40-6:30&quot;,
        ///        &quot;6:30-7:20&quot;,
        ///        &quot;7:20-7:40&quot;,
        ///        &quot;7:45-8:35&quot;,
        ///        &quot;8:35-9:45&quot;
        ///    ]
        ///
        ///.
        /// </summary>
        public static string MWFTimes {
            get {
                return ResourceManager.GetString("MWFTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	[
        ///        &quot;3:50-4:40&quot;,
        ///        &quot;4:40-5:30&quot;,
        ///        &quot;5:30-6:20&quot;,
        ///        &quot;6:25-7:15&quot;,
        ///        &quot;7:15-8:05&quot;,
        ///        &quot;8:05-9:25&quot;
        ///    ].
        /// </summary>
        public static string TRTimes {
            get {
                return ResourceManager.GetString("TRTimes", resourceCulture);
            }
        }
    }
}
