//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLSScheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLSScheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;LSA-1&quot; : {
        ///&quot;1&quot;:&quot;Facts about Sloths&quot;,
        ///&quot;2&quot;:&quot;Gladiators&quot;,
        ///&quot;3&quot;:&quot;Meet Joey&quot;,
        ///&quot;4&quot;:&quot;Your ID, Please!&quot;,
        ///&quot;5&quot;:&quot;Don&apos;t Bite Me!&quot;,
        ///&quot;6&quot;:&quot;Get the Ball Rolling&quot;,
        ///&quot;7&quot;:&quot;Why Do We Sleep?&quot;,
        ///&quot;8&quot;:&quot;Saving Energy&quot;
        ///},
        ///
        ///&quot;LSA-2&quot; : {
        ///&quot;1&quot;:&quot;Pyramids&quot;,
        ///&quot;2&quot;:&quot;Moko to the Rescue&quot;,
        ///&quot;3&quot;:&quot;Which is Colder?&quot;,
        ///&quot;4&quot;:&quot;Reading Dots&quot;,
        ///&quot;5&quot;:&quot;Wasps and Bees&quot;,
        ///&quot;6&quot;:&quot;You Can Be a Potato Farmer&quot;,
        ///&quot;7&quot;:&quot;Grand Canyon&quot;,
        ///&quot;8&quot;:&quot;A New Life for Trash&quot;
        ///	},
        ///
        ///&quot;LSB-1&quot; : {
        ///&quot;1&quot;:&quot;Sweet Midas&quot;,
        ///&quot;2&quot;:&quot;Mayonnaise By Accident&quot;,
        ///&quot;3&quot;:&quot;Inside a Mommy&apos;s  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    &quot;DSC&quot;,
        ///    &quot;DSD&quot;,
        ///    &quot;LSA-1&quot;,
        ///    &quot;LSA-2&quot;,
        ///    &quot;LSB-1&quot;,
        ///    &quot;LSB-2&quot;,
        ///    &quot;LSC-1&quot;,
        ///    &quot;LSC-2&quot;,
        ///    &quot;LSD-1&quot;,
        ///    &quot;LSD-2&quot;,
        ///    &quot;MSA1&quot;,
        ///    &quot;MSA-2&quot;,
        ///    &quot;MSB-1&quot;,
        ///    &quot;MSB2&quot;
        ///].
        /// </summary>
        internal static string ClassLevels {
            get {
                return ResourceManager.GetString("ClassLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	[
        ///        &quot;2:30-3:10&quot;,
        ///        &quot;3:10-3:50&quot;,
        ///        &quot;3:55-4:45&quot;,
        ///        &quot;4:45-5:35&quot;,
        ///        &quot;5:40-6:30&quot;,
        ///        &quot;6:30-7:20&quot;,
        ///        &quot;7:20-7:40&quot;,
        ///        &quot;7:45-8:35&quot;,
        ///        &quot;8:35-9:45&quot;
        ///    ]
        ///
        ///.
        /// </summary>
        internal static string MWFTimes {
            get {
                return ResourceManager.GetString("MWFTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	[
        ///        &quot;3:50-4:40&quot;,
        ///        &quot;4:40-5:30&quot;,
        ///        &quot;5:30-6:20&quot;,
        ///        &quot;6:25-7:15&quot;,
        ///        &quot;7:15-8:05&quot;,
        ///        &quot;8:05-9:25&quot;
        ///    ].
        /// </summary>
        internal static string TRTimes {
            get {
                return ResourceManager.GetString("TRTimes", resourceCulture);
            }
        }
    }
}
